<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-RKD26HG" failures="2" tests="4" name="EdgeTest" time="44.971" errors="0" timestamp="2024-10-02T21:26:09 IST">
  <testcase classname="testCases.TC001_AccountRegistration_test" name="verify_account_registration" time="4.305"/>
  <testcase classname="testCases.TC003_LoginDD_Test" name="verifyDataDrivenTest" time="2.399"/>
  <testcase classname="testCases.TC003_LoginDD_Test" name="verifyDataDrivenTest" time="11.658">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_LoginDD_Test.verifyDataDrivenTest(TC003_LoginDD_Test.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verifyDataDrivenTest -->
  <testcase classname="testCases.TC003_LoginDD_Test" name="verifyDataDrivenTest" time="11.408">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_LoginDD_Test.verifyDataDrivenTest(TC003_LoginDD_Test.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verifyDataDrivenTest -->
</testsuite> <!-- EdgeTest -->
